### DISCUSSION TITLE
Running port

### DISCUSSION THREAD

**Discussion by mavismmg** [postgis/docker-postgis#385] [Q&A]
Is there a way to run postgis in port 5433 instead of 5432?

**Comment by mavismmg** [comment]
```
services:
  testdb_postgis:
    restart: always
    image: postgis/postgis:13-3.2-alpine
    container_name: testdb
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
```
