### ISSUE TITLE
permissions issue when I switch from postgres(official) to this postgis:11-alpine build

### ISSUE THREAD

**Issue by 9Dave9** [postgis/docker-postgis#131]
Hi, 

Using the docker for mac app. Just installed everything yesterday. Finally got the app going.
But I can't run migrations till I install `postgis`. So I dropped the `postgres` dockerhub image for your `postgis:11-alpine` image. But I keep on getting a `permission denied` issue when docker tries to `mkdir` for the pg_data volume.

Dockerfile:

```
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: gametime_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024

  db:
    # We use the predefined Postgres image
    image: mdillon/postgis:11-alpine
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/usr/local/var/postgres_data
# Define the volumes
volumes:
  pgdata:

```

Error I'm getting:
```
db_1       | mkdir: can't create directory '/var/lib/postgresql/data/pgdata': Permission denied
```

This does not happen though when using the `postgres` image. I have googled high and low. I did read something about Docker for Mac running commands on the containers it creates in a VM as the current user's localhost and not root. But that doesn't make sense to me - how do I get around this, if that's the case?

Appreciate the the time - in advance.

David

[Extra note:] - I did try the `<path to source dir>:z` and `<path to source dir>:Z` - still got the exact same error as above.
