### ISSUE TITLE
could not open extension control file "/address_standardizer.control"

### ISSUE THREAD

**Issue by saeed-vayghan** [postgis/docker-postgis#145]
```
~# CREATE EXTENSION IF NOT EXISTS postgis;
NOTICE:  extension "postgis" already exists, skipping
CREATE EXTENSION


~# CREATE EXTENSION IF NOT EXISTS address_standardizer WITH SCHEMA public;
ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/address_standardizer.control": No such file or directory
```
How can i enable `address_standardizer` extension?

This is my docker-compose.yml
```
version: '3'

services:
  postgres:
    container_name: 'postgres-rechat-server'
    image: 'mdillon/postgis:10-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'changeme'
      PGDATA: '/data/postgres'
    volumes:
       - './postgres:/data/postgres'
    ports:
      - '5432:5432'
    networks:
      - 'postgres'
    restart: 'always'
```
