### ISSUE TITLE
incorrect ctype and collation in database

### ISSUE THREAD

**Issue by UlrichKnaack** [postgis/docker-postgis#198]
I've tried to apply german character encoding in my database, but I got `C.UTF-8`.
This is my setup:

```
version: "3"

services:
    pgis:
        image: postgis/postgis:12-3.0
        container_name: pgis
        volumes:
            - pgisdb:/var/lib/postgresql/data/
            - ./init/:/docker-entrypoint-initdb.d/
            # - ./init/sql/:/docker-entrypoint-initdb.d/sql/
        ports:
            - "5432:5432"
        restart: always
        env_file: env-pgis

    pgadmin4:
        image: dpage/pgadmin4:4.21
        volumes:
            - pgadmin4:/pgadmin4
            - pgadmin4lib:/var/lib/pgadmin
        ports:
            - "8085:80"
        env_file: env-pgadmin

volumes:
    pgisdb:
    pgadmin4:
    pgadmin4lib:
    init:
```

env-pgis:

```
POSTGRES_USER=bop
POSTGRES_PASSWORD=mypass
POSTGRES_DBNAME=pgis
DEFAULT_COLLATION=de_DE.UTF-8
DEFAULT_CTYPE=de_DE.UTF-8
DEFAULT_ENCODIG=UTF8
```

Output (extract) from `docker-compose logs`:  
```
pgis        | The database cluster will be initialized with locale "en_US.utf8".
pgis        | The default database encoding has accordingly been set to "UTF8".
pgis        | The default text search configuration will be set to "english".
```
