### ISSUE TITLE
var/lib/postgres/data no permission

### ISSUE THREAD

**Issue by daweimau** [postgis/docker-postgis#361]
Given the below docker-compose yml:

```yml
version: "3.7"

services:
    db:
        container_name: db
        image: postgis/postgis:15-3.4-alpine
        ports:
            - "5010:5432"  
        environment:
            POSTGRES_DB: my-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: verysecretpass
        volumes:
            - ./pgdata:/var/lib/postgresql/data 
```

* If we replace `image` with `postgres:alpine`, we have no issues. Everything works.
* If we use `postgis/postgis:15-3.4-alpine`, building the image seems ok, and first run also seems ok. Subsequent runs with `docker compose up db` will produce this error:

```
db  | 2023-09-17 01:22:45.415 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
db  | 2023-09-17 01:22:45.415 UTC [1] HINT:  The server must be started by the user that owns the data directory.
```

## But it works with the postgres alpine image. Why should it not work now?

Seeing as we extend the postgres-alpine image, and postgres-alpine works, I figured we must be introducing the problem after the base image layers / entrypoint.

* Copied down the [postgis alpine Dockerfile and sh scripts](https://github.com/postgis/docker-postgis/tree/master/15-3.4/alpine), and adjusted docker-compose.yml to build from a local image instead:

```yml
    db:
        container_name: db
        build:
            context: "./pg"
            dockerfile: "./Dockerfile"
        ports:
```

* Then ran into #360 
* However, noticed even with this separate issue, I could still repro the error I cared about: `data directory "/var/lib/postgresql/data" has wrong ownership`
* For completeness, decided to try getting around #360 before resuming this issue
* Implemented my workaround for #360 as described [here](https://github.com/postgis/docker-postgis/issues/360#issuecomment-1722358956)

**Since doing so, the `data directory "/var/lib/postgresql/data" has wrong ownership` error has disappeared.**

I don't understand the details. But I believe the `initdb-postgis.sh` script is doing it
